import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} main_body `}>
        {/* <img className="w-full h-full bg_img" style={{objectFit:"contain"}} src="./bg_img.png" alt="img" /> */}
        {children}
      </body>
    </html>
  );
}
